### PR TITLE
Fix and reorganize all config files

### LINKED ISSUE #596: Fix all config files for SQLite
Because of #584 all config files need to be fixed, and reorganized if necessary.

### PR DESCRIPTION
**Pull request by b1ron**
Closes #596.

### CODE REVIEW

**Comment by b1ron** [comment]
@AlekSi CI seems to be in a somewhat broken state with 13 expected checks for `ferretdb`.

File: internal/configload/configload.go [hunk 1]
```diff
@@ -37,7 +37,7 @@ type config struct {
 		// Includes is a mapping that allows us to merge sequences together,
 		// which is currently not possible in the YAML spec - https://github.com/yaml/yaml/issues/48
 		Includes   map[string][]string `yaml:"includes"`
-		PostgreSQL *testConfig         `yaml:"ferretdb"` // TODO preserving YAML tag for compatibility, will update later
+		PostgreSQL *testConfig         `yaml:"postgresql"`
```
Comment (AlekSi) [inline internal/configload/configload.go:40]: Please move code all code changes into a separate PR

**Comment by b1ron** [comment]
workload A on SQLite is an order of magnitude slower than the read-only workload B, this will be helpful to measure performance.

**Review by AlekSi — APPROVED** [review]
