### PR TITLE
Use `common` configuration section more

### LINKED ISSUE #142: Use `common` configuration section more
Currently, we don't use `common` section if `ferretdb` and `mongodb` sections are used:
https://github.com/FerretDB/dance/blob/edf7f8560a91eeadabf39b25b189c13aa392ce88/internal/config.go#L73-L75

We should allow `common.pass`, `common.skip` and `common.fail` to be non-empty. They should be merged into matching `ferretdb` and `mongodb` sections.

`common.default` and `common.stats` should remain empty if `ferretdb` or `mongodb` section is set (or both of them).

### PR DESCRIPTION
**Pull request by noisersup**
### TODO:
- [x] tests
- [x] functionality

Closes #142.

### CODE REVIEW

File: internal/config.go [hunk 1]
```diff
@@ -65,14 +66,37 @@ func LoadConfig(path string) (*Config, error) {
 }
 
 func (c *Config) fillAndValidate() error {
-	if c.Results.Common == nil {
-		if c.Results.FerretDB == nil || c.Results.MongoDB == nil {
-			return fmt.Errorf("both FerretDB and MongoDB results must be set (if common results are not set)")
+	if c.Results.Common != nil {
```
Comment (seeforschauer) [inline internal/config.go:69]: Let's move this to a separate function called `merge...` smth.

File: internal/config_test.go [hunk 2]
```diff
@@ -0,0 +1,221 @@
...
+
+func TestFillAndValidate(t *testing.T) {
+	t.Parallel()
+
+	for name, tc := range map[string]struct {
+		in          *Results
+		expected    *Results
+		expectedErr error
+	}{
+		"FillAndValidate_Filled": {
```
Comment (seeforschauer) [inline internal/config_test.go:32]: Would you please don't use the underscores in test names? I mean, for the code consistency.

File: internal/tests_config.go [hunk 3]
```diff
@@ -54,11 +54,9 @@ type Stats struct {
 // TestsConfig represents a part of the dance configuration for tests.
 //
 // May contain prefixes; the longest prefix wins.
-//
-//nolint:govet // we don't care about alignment there
 type TestsConfig struct {
 	Default status   `yaml:"default"`
-	Stats   Stats    `yaml:"stats"`
+	Stats   *Stats   `yaml:"stats"`
```
Comment (seeforschauer) [inline internal/tests_config.go:59]: What do mean stats? Let's add a comment.

File: internal/config_test.go (hunk 2 above)
Comment (w84thesun) [reply internal/config_test.go:32]: https://github.com/FerretDB/FerretDB/issues/694

**Review by w84thesun — APPROVED** [review]
LGTM, except those tests names.

File: internal/tests_config.go (hunk 3 above)
Comment (noisersup) [reply internal/tests_config.go:59]: The `Stats` struct is defined above it. Do you prefer to add a comment above the `Stats` struct, or next to this field?

**Comment by seeforschauer** [comment]
@noisersup linters not passing.

File: internal/config.go [hunk 4]
```diff
@@ -64,15 +65,42 @@ func LoadConfig(path string) (*Config, error) {
...
+
+		ferretdb.Pass = append(ferretdb.Pass, common.Pass...)
+		mongodb.Pass = append(mongodb.Pass, common.Pass...)
+
+		if common.Default != "" {
+			if ferretdb.Default != "" || mongodb.Default != "" {
+				return errors.New("default value cannot be set in common, when it's set in database")
+			}
+			ferretdb.Default = common.Default
+			mongodb.Default = common.Default
```
Comment (seeforschauer) [inline internal/config.go:85]: remove cyclomatic complexity, do `return`.

File: internal/config.go [hunk 5]
```diff
@@ -64,15 +65,42 @@ func LoadConfig(path string) (*Config, error) {
...
-	} else {
-		if c.Results.FerretDB != nil || c.Results.MongoDB != nil {
-			return fmt.Errorf("common results are not allowed with FerretDB or MongoDB results")
+
+		if common.Stats != nil {
+			if ferretdb.Stats != nil || mongodb.Stats != nil {
+				return errors.New("stats value cannot be set in common, when it's set in database")
+			}
+			ferretdb.Stats = common.Stats
+			mongodb.Stats = common.Stats
```
Comment (seeforschauer) [inline internal/config.go:93]: and here.

**Comment by noisersup** [comment]
> @noisersup linters not passing.

Sorry, I forgot. Fixed!

File: internal/config.go [hunk 6]
```diff
@@ -64,15 +65,42 @@ func LoadConfig(path string) (*Config, error) {
 	return &c, nil
 }
 
-func (c *Config) fillAndValidate() error {
-	if c.Results.Common == nil {
-		if c.Results.FerretDB == nil || c.Results.MongoDB == nil {
-			return fmt.Errorf("both FerretDB and MongoDB results must be set (if common results are not set)")
+// Merge common config with both databases.
```
Comment (seeforschauer) [inline internal/config.go:68]: @noisersup  well, here if a linter for unexported funcs will be enabled, it will argue that the comment doesn't start with the func name. 
```suggestion
// mergeTestConfigs merges common config with both databases test configs.
```

File: internal/config.go (hunk 4 above)
Comment (noisersup) [reply internal/config.go:85]: I don't quite understand. What if `Default` and `Stats` are both set in common?

Comment (seeforschauer) [reply internal/config.go:85]: > I don't quite understand. What if `Default` and `Stats` are both set in common?

Let's have a talk.

**Review by seeforschauer — DISMISSED** [review]

**Review by w84thesun — DISMISSED** [review]

**Review by seeforschauer — APPROVED** [review]

**Review by w84thesun — APPROVED** [review]

File: internal/config.go [hunk 7]
```diff
@@ -64,15 +65,42 @@ func LoadConfig(path string) (*Config, error) {
...
-			return fmt.Errorf("common results are not allowed with FerretDB or MongoDB results")
+
+		if common.Stats != nil {
+			if ferretdb.Stats != nil || mongodb.Stats != nil {
+				return errors.New("stats value cannot be set in common, when it's set in database")
+			}
+			ferretdb.Stats = common.Stats
+			mongodb.Stats = common.Stats
 		}
+	} else if ferretdb == nil || mongodb == nil {
```
Comment (AlekSi) [inline internal/config.go:95]: `else if` is a big smell.

IIUC, that could be replaced with:
```go
if common == nil {
  if ferretdb == nil || mongodb == nil {
    return fmt.Errorf("both FerretDB and MongoDB results must be set (if common results are not set)")
  }
  return nil
}

// the rest
```

File: internal/config.go [hunk 8]
```diff
@@ -64,15 +65,42 @@ func LoadConfig(path string) (*Config, error) {
 	return &c, nil
 }
 
-func (c *Config) fillAndValidate() error {
-	if c.Results.Common == nil {
-		if c.Results.FerretDB == nil || c.Results.MongoDB == nil {
-			return fmt.Errorf("both FerretDB and MongoDB results must be set (if common results are not set)")
+// mergeTestConfigs merges common config with both databases test configs.
```
Comment (AlekSi) [inline internal/config.go:68]:
```suggestion
// mergeTestConfigs merges common config into both databases test configs.
```

To indicate direction

File: tests/mongo-go-driver.yml [hunk 9]
```diff
@@ -12,48 +12,8 @@ args:
...
-      - go.mongodb.org/mongo-driver/x/mongo/driver/integration/TestAggregate/AllowDiskUse
-      - go.mongodb.org/mongo-driver/x/mongo/driver/integration/TestAggregate/Multiple_Batches
-      - go.mongodb.org/mongo-driver/x/mongo/driver/integration/TestAggregate/TestMaxTimeMSInGetMore
-      - go.mongodb.org/mongo-driver/mongo/TestClient/endSessions/number_of_sessions_divides_evenly
-      - go.mongodb.org/mongo-driver/mongo/TestClient/endSessions/number_of_sessions_does_not_divide_evenly
-      - go.mongodb.org/mongo-driver/mongo/TestClient/endSessions
-      - go.mongodb.org/mongo-driver/mongo/TestClient
-
-    skip: # shared with mongodb
+  common: # shared between ferretdb and mongodb
```
Comment (AlekSi) [inline tests/mongo-go-driver.yml:15]:
```suggestion
  common:
```

That comment was there to indicate that this section should be synced manually, but that's no longer need, and the name "common" is clear enough

**Review by w84thesun — APPROVED** [review]

**Review by seeforschauer — APPROVED** [review]

**Review by AlekSi — APPROVED** [review]
